# Generated by Django 2.0.6 on 2018-07-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='datetimestamp', max_length=20)),
                ('record_type', models.FloatField(max_length=5, null=True)),
                ('historic_glucose', models.FloatField(max_length=5, null=True)),
                ('scan_glucose', models.FloatField(max_length=5, null=True)),
                ('rapid_acting_insulin', models.FloatField(max_length=5, null=True)),
                ('carbohydrates', models.FloatField(max_length=5, null=True)),
                ('notes', models.CharField(default='Normal Day Shift', max_length=20)),
            ],
        ),
    ]
