# Generated by Django 2.0.6 on 2018-08-01 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resInput.middleware.current_user


class Migration(migrations.Migration):

    dependencies = [
        ('resInput', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='user',
        ),
        migrations.AlterField(
            model_name='input',
            name='created_by',
            field=models.ForeignKey(default=resInput.middleware.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
