# Generated by Django 2.0.6 on 2018-08-01 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resInput', '0002_auto_20180801_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='created_by',
        ),
        migrations.AddField(
            model_name='input',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
